name: Code Style

on:
        push:
                branches:
                        - *
        pull_request:

jobs:
        php:
                name: PHP CodeSniffer
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - run: git clone --branch="5.3" --depth=1 --quiet git://github.com/WoltLab/WCF.git com.woltlab.wcf
                        - uses: chekalsky/phpcs-action@v1
